---
- name: Install package build and runtime dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - debhelper
    - dh-systemd
    - libcapture-tiny-perl
    - libconfig-inifiles-perl
    - pv
    - lzop
    - mbuffer

- name: Clone sanoid
  git:
    repo: "https://github.com/jimsalterjrs/sanoid"
    dest: /tmp/ansible-role-sanoid/sanoid
    force: true
    version: "v{{ sanoid_git_tag }}"
  changed_when: false
  become: false

- name: Create symlink to debian in repo root dir
  file:
    src: /tmp/ansible-role-sanoid/sanoid/packages/debian
    dest: /tmp/ansible-role-sanoid/sanoid/debian
    state: link

- name: Build Debian Package
  shell: dpkg-buildpackage -uc -us
    chdir: /tmp/ansible-role-sanoid/sanoid

- name: Install sanoid deb file
  apt:
    deb: "/tmp/ansible-role-sanoid/sanoid_{{ sanoid_git_tag }} _all.deb"
